repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
      files: ^tuplex/python/tuplex.*\.py$
    - id: end-of-file-fixer
      files: ^tuplex/python/tuplex.*\.py$
    - id: trailing-whitespace
      files: ^tuplex/python/tuplex.*\.py$
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.9
  hooks:
    # Run the linter.
    - id: ruff
      files: ^tuplex/python/tuplex.*\.py$
      args: [ "--fix", "--select", "I" ]
      types_or: [ python, pyi ]
    # Run the formatter.
    - id: ruff-format
      files: ^tuplex/python/tuplex.*\.py$
      types_or: [ python, pyi ]