repos:
#- repo: https://github.com/pre-commit/pre-commit-hooks
#  rev: v2.3.0
#  hooks:
#    - id: check-yaml
#      exclude: ["tuplex/test/resources"]
#    - id: end-of-file-fixer
#      exclude: ["tuplex/test/resources"]
#    - id: trailing-whitespace
#      exclude: ["tuplex/test/resources"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.9
  hooks:
    # Run the linter.
    - id: ruff
      files: ^tuplex/python/tuplex.*\.py$
      args: [ --fix ]
      types_or: [ python, pyi ]
    # Run the formatter.
    - id: ruff-format
      files: ^tuplex/python/tuplex.*\.py$
      types_or: [ python, pyi ]